targets:
  $default:
    builders:
      freezed:
        enabled: true
      json_serializable:
        enabled: true
      riverpod_generator:
        enabled: true
      hive_generator:
        enabled: true
